In [78]:
import pandas as pd
import numpy as np

pd.options.display.max_columns = 50

In [2]:
train_df = pd.read_csv('../data/dacon_veg/train/train.csv')
train_meta_1 = pd.read_csv('../data/dacon_veg/train/meta/TRAIN_산지공판장_2018-2021.csv')
train_meta_2 = pd.read_csv('../data/dacon_veg/train/meta/TRAIN_전국도매_2018-2021.csv')

In [15]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29376 entries, 0 to 29375
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   시점          29376 non-null  object
 1   품목명         29376 non-null  object
 2   품종명         29376 non-null  object
 3   거래단위        29376 non-null  object
 4   등급          29376 non-null  object
 5   평년 평균가격(원)  29376 non-null  float64
 6   평균가격(원)     29376 non-null  float64
dtypes: float64(2), object(5)
memory usage: 1.6+ MB

In [17]:
train_df['품목명'].nunique()

10

In [14]:
train_df[(train_df['품목명']=='감자') & (train_df['품종명']== '감자 수미') & (train_df['등급']== '상')]

            시점 품목명    품종명    거래단위 등급    평년 평균가격(원)       평균가격(원)
1872  201801상순  감자  감자 수미  20키로상자  상  24660.031746  44170.285714
1873  201801중순  감자  감자 수미  20키로상자  상  23299.444444  48283.777778
1874  201801하순  감자  감자 수미  20키로상자  상  25218.007407  50243.000000
1875  201802상순  감자  감자 수미  20키로상자  상  28703.875000  55380.666667
1876  201802중순  감자  감자 수미  20키로상자  상  27419.882275  59133.000000
...        ...  ..    ...     ... ..           ...           ...
2011  202111중순  감자  감자 수미  20키로상자  상  30634.777778  33761.333333
2012  202111하순  감자  감자 수미  20키로상자  상  32139.787037  36023.875000
2013  202112상순  감자  감자 수미  20키로상자  상  31688.643519  35233.666667
2014  202112중순  감자  감자 수미  20키로상자  상  33251.916667  32679.125000
2015  202112하순  감자  감자 수미  20키로상자  상  34313.181481  42440.600000

[144 rows x 7 columns]

In [25]:
train_meta_1.head(1)

,시점,공판장코드,공판장명,품목코드,품목명,품종코드,품종명,등급코드,등급명,총반입량(kg),...,평균가(원/kg),중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
0,201801상순,1000000000,*전국농협공판장,501,감자,50101,수미,11,특,15470.0,...,1712.637363,1723.961039,1545.454545,2320.666667,7,1947.350427,1769.85832,1023.982379,0.0,2018

In [19]:
train_meta_1['품목명'].unique() # 건고추가 없다

array(['감자', '사과', '배', '배추', '상추', '무', '양파', '대파', '마늘', '순무'],
      dtype=object)

In [53]:
potato = train_meta_1[(train_meta_1['품목명']=='감자') & (train_meta_1['품종명']=='수미')]
potato.groupby('공판장명').count()

,시점,공판장코드,품목코드,품목명,품종코드,품종명,등급코드,등급명,총반입량(kg),총거래금액(원),평균가(원/kg),중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
공판장명,,,,,,,,,,,,,,,,,,,,
*전국농협공판장,805,805,805,805,805,805,805,805,805,805,805,805,805,805,805,805,805,805,805,805
거창사과원예농협,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
경주농협 공판장,185,185,185,185,185,185,185,185,185,185,185,185,185,185,185,185,185,185,185,185
군산원예농업협동조합,398,398,398,398,398,398,398,398,398,398,398,398,398,398,398,398,398,398,398,398
김제원예농업협동조합공판장,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22,22
김천농협공판장,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88,88
나주배농업협동조합,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3
남원원협공판장,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200,200
논산계룡농협농산물공판장,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
대관령원예농협공판사업소,210,210,210,210,210,210,210,210,210,210,210,210,210,210,210,210,210,210,210,210
대구공판장,237,237,237,237,237,237,237,237,237,237,237,237,237,237,237,237,237,237,237,237
동남해농협 삼동지점(공판),1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
동두천농협공판장,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79
목포원예농업협동조합,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106,106
삼천포농협농산물공판장,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29,29
상주농협공판장,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184,184
상주원예농협공판장,259,259,259,259,259,259,259,259,259,259,259,259,259,259,259,259,259,259,259,259
서포농협(공판),96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96,96
여수원예농협농산물공판장,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104,104
여수원예농협여천공판장,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35,35
영천농협농산물공판장간이지점,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28,28
예산능금농협공판장,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2
의성농협농산물공판장(공판),4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4
의성중부농협경매식집하장(공판),7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
전주농협공판장,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79,79
점촌농협경제사업소,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17,17
제주시농협농산물공판장,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7
제천농협공판장,674,674,674,674,674,674,674,674,674,674,674,674,674,674,674,674,674,674,674,674
충서원협농산물공판장,377,377,377,377,377,377,377,377,377,377,377,377,377,377,377,377,377,377,377,377
포천농협공판장,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350,350

In [74]:
potato = train_meta_1[(train_meta_1['품목명']=='감자') & (train_meta_1['품종명']== '수미') & (train_meta_1['등급명']== '상')]
potato.describe()

,공판장코드,품목코드,품종코드,등급코드,총반입량(kg),총거래금액(원),평균가(원/kg),중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
count,7.730000e+02,773.0,773.0,773.0,773.000000,7.730000e+02,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000,773.000000
mean,3.102088e+09,501.0,50101.0,12.0,1749.715395,1.497758e+06,807.472168,780.053739,586.226113,1031.232588,7.182406,629.376854,586.644513,625.513115,101.154268,2019.450194
std,1.462583e+09,0.0,0.0,0.0,3381.991023,3.123969e+06,692.497518,684.097175,658.506332,815.891370,9.602817,689.006799,581.568004,570.056928,271.020893,1.122851
min,1.000000e+09,501.0,50101.0,12.0,1.000000,1.000000e+03,50.000000,50.000000,50.000000,50.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2018.000000
25%,1.278201e+09,501.0,50101.0,12.0,120.000000,7.700000e+04,425.000000,383.125000,220.000000,590.000000,2.000000,165.000000,0.000000,150.000000,0.000000,2018.000000
50%,3.048206e+09,501.0,50101.0,12.0,610.000000,3.940000e+05,650.000000,650.000000,403.444444,885.526316,4.000000,544.256757,508.411215,558.995065,0.000000,2019.000000
75%,4.128509e+09,501.0,50101.0,12.0,1860.000000,1.298000e+06,1000.000000,996.888889,747.916667,1300.000000,8.000000,883.678161,865.666667,909.558824,0.000000,2020.000000
max,6.198200e+09,501.0,50101.0,12.0,31035.000000,2.715660e+07,11075.000000,11181.250000,10862.500000,11500.000000,91.000000,11075.000000,3527.708333,3527.708333,1535.497835,2021.000000

In [75]:
potato

,시점,공판장코드,공판장명,품목코드,품목명,품종코드,품종명,등급코드,등급명,총반입량(kg),...,평균가(원/kg),중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
1,201801상순,1000000000,*전국농협공판장,501,감자,50101,수미,12,상,2900.0,...,1198.655172,1252.737207,893.055556,1417.857143,4,1301.239669,1348.253676,571.311475,0.000000,2018
156,201801상순,3048206353,제천농협공판장,501,감자,50101,수미,12,상,1940.0,...,1049.536082,1037.063492,880.789474,1417.857143,14,1285.652174,816.379310,598.584906,0.000000,2018
381,201801상순,4128509458,대구공판장,501,감자,50101,수미,12,상,960.0,...,1500.000000,1500.000000,1500.000000,1500.000000,1,0.000000,1004.347826,0.000000,0.000000,2018
617,201801중순,1000000000,*전국농협공판장,501,감자,50101,수미,12,상,1710.0,...,1219.766082,1065.875000,896.865672,1612.941176,6,1198.655172,1189.253731,521.194690,0.000000,2018
753,201801중순,3048206353,제천농협공판장,501,감자,50101,수미,12,상,1460.0,...,1157.054795,837.822581,400.000000,1648.000000,10,1049.536082,1421.304348,543.383838,0.000000,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117423,202112중순,3108203711,충서원협농산물공판장,501,감자,50101,수미,12,상,20.0,...,900.000000,900.000000,900.000000,900.000000,1,0.000000,0.000000,0.000000,0.000000,2021
117931,202112하순,1000000000,*전국농협공판장,501,감자,50101,수미,12,상,1490.0,...,488.724832,290.000000,136.666667,697.974684,6,538.139535,773.409091,388.660377,597.482358,2021
118090,202112하순,3048206353,제천농협공판장,501,감자,50101,수미,12,상,1280.0,...,435.781250,290.000000,136.666667,656.896552,11,533.882353,775.526316,388.660377,582.094770,2021
118150,202112하순,3108203711,충서원협농산물공판장,501,감자,50101,수미,12,상,80.0,...,700.000000,700.000000,700.000000,700.000000,1,900.000000,0.000000,0.000000,0.000000,2021
118188,202112하순,4018200719,군산원예농업협동조합,501,감자,50101,수미,12,상,130.0,...,880.000000,880.000000,880.000000,880.000000,1,0.000000,420.000000,0.000000,0.000000,2021

In [70]:
# potato.drop(['공판장코드', '공판장명', '품목코드', '품종코드', '품종명', '등급코드', '등급명',], axis=1, inplace=True)

/var/folders/xg/fp1_kg411bl0yfm4mg9jjycm0000gn/T/ipykernel_31900/4106679806.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  potato.drop(['공판장코드', '공판장명', '품목코드', '품종코드', '품종명', '등급코드', '등급명',], axis=1, inplace=True)

In [76]:
potato_df = potato.groupby(['시점', '품목명']).mean(numeric_only=True).reset_index()
potato_df

,시점,품목명,공판장코드,품목코드,품종코드,등급코드,총반입량(kg),총거래금액(원),평균가(원/kg),중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
0,201801상순,감자,2.725572e+09,501.0,50101.0,12.0,1933.333333,2.317400e+06,1249.397085,1263.266900,1091.281676,1445.238095,6.333333,862.297281,1056.326938,389.965460,0.000000,2018.0
1,201801중순,감자,3.281153e+09,501.0,50101.0,12.0,855.000000,1.042900e+06,1491.229029,1353.424395,1174.216418,1777.735294,5.750000,562.047814,1010.139520,453.644632,0.000000,2018.0
2,201801하순,감자,2.688802e+09,501.0,50101.0,12.0,646.666667,9.343333e+05,1527.182496,1794.000000,1395.588235,2200.000000,3.333333,1288.305371,862.297281,303.838384,0.000000,2018.0
3,201802상순,감자,2.725572e+09,501.0,50101.0,12.0,6000.000000,8.652067e+06,1361.544180,1187.537879,616.666667,1686.836158,6.000000,960.515829,1249.397085,673.328812,0.000000,2018.0
4,201802중순,감자,2.024103e+09,501.0,50101.0,12.0,1040.000000,1.298000e+06,1248.076923,1098.214286,475.000000,2100.000000,4.000000,1273.030556,1188.410438,885.164835,0.000000,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,202111중순,감자,2.892562e+09,501.0,50101.0,12.0,276.000000,8.880000e+04,419.400458,424.846154,401.384615,534.000000,2.200000,382.201218,316.342543,380.203478,356.511728,2021.0
138,202111하순,감자,2.336152e+09,501.0,50101.0,12.0,220.000000,1.701500e+05,767.233852,716.093750,532.500000,811.875000,2.250000,304.250572,580.999540,403.674097,316.921008,2021.0
139,202112상순,감자,2.024103e+09,501.0,50101.0,12.0,2520.000000,1.842600e+06,731.190476,765.000000,150.000000,827.500000,12.500000,774.467703,511.753044,308.034091,496.450860,2021.0
140,202112중순,감자,2.385470e+09,501.0,50101.0,12.0,1146.666667,6.170667e+05,657.340629,636.980676,448.888889,869.827586,7.000000,487.460317,189.000763,274.912281,472.702438,2021.0
141,202112하순,감자,2.793653e+09,501.0,50101.0,12.0,745.000000,3.641000e+05,626.126521,540.000000,463.333333,733.717809,4.750000,493.005472,492.233852,194.330189,294.894282,2021.0

In [67]:
train_df[(train_df['품목명']=='감자') & (train_df['품종명']== '감자 수미') & (train_df['등급']== '상')]

            시점 품목명    품종명    거래단위 등급    평년 평균가격(원)       평균가격(원)
1872  201801상순  감자  감자 수미  20키로상자  상  24660.031746  44170.285714
1873  201801중순  감자  감자 수미  20키로상자  상  23299.444444  48283.777778
1874  201801하순  감자  감자 수미  20키로상자  상  25218.007407  50243.000000
1875  201802상순  감자  감자 수미  20키로상자  상  28703.875000  55380.666667
1876  201802중순  감자  감자 수미  20키로상자  상  27419.882275  59133.000000
...        ...  ..    ...     ... ..           ...           ...
2011  202111중순  감자  감자 수미  20키로상자  상  30634.777778  33761.333333
2012  202111하순  감자  감자 수미  20키로상자  상  32139.787037  36023.875000
2013  202112상순  감자  감자 수미  20키로상자  상  31688.643519  35233.666667
2014  202112중순  감자  감자 수미  20키로상자  상  33251.916667  32679.125000
2015  202112하순  감자  감자 수미  20키로상자  상  34313.181481  42440.600000

[144 rows x 7 columns]

In [79]:
train_meta_2.head(1)

,시점,시장코드,시장명,품목코드,품목명,품종코드,품종명,총반입량(kg),총거래금액(원),평균가(원/kg),고가(20%) 평균가,중가(60%) 평균가,저가(20%) 평균가,중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
0,201801상순,100000,*전국도매시장,501,감자,50124,깐감자,20.0,86520,4326.0,0.0,0.0,4326.0,4326.0,4326.0,4326.0,1,0.0,4009.0,0.0,0.0,2018

In [82]:
potato1 = train_meta_2[(train_meta_2['품목명']=='감자') & (train_meta_2['품종명']== '수미')]
potato1

,시점,시장코드,시장명,품목코드,품목명,품종코드,품종명,총반입량(kg),총거래금액(원),평균가(원/kg),고가(20%) 평균가,중가(60%) 평균가,저가(20%) 평균가,중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
8,201801상순,100000,*전국도매시장,501,감자,50101,수미,2423696.5,4135898623,1706.442462,2415.326746,1751.312256,867.893389,1261.000000,0.000000,9859.633333,1229,168039.623201,27204.818622,22433.563798,18536.038912,2018
113,201801상순,110001,서울가락,501,감자,50101,수미,1272705.5,2110894450,1658.588299,2300.540183,1712.434473,895.708161,1425.000000,50.000000,3500.000000,355,28447.177502,25270.124064,21525.673046,17081.723834,2018
161,201801상순,110008,서울강서,501,감자,50101,수미,70320.0,112287500,1596.807452,1948.205128,1761.951567,1175.552721,950.000000,400.000000,1979.867987,31,30918.106771,25443.441433,23757.961783,0.000000,2018
191,201801상순,210001,부산엄궁,501,감자,50101,수미,105020.0,178672800,1701.321653,2195.781638,1868.360873,1176.740918,777.884615,150.000000,2250.000000,38,35521.170813,29637.598242,24943.970683,20202.840920,2018
233,201801상순,210009,부산반여,501,감자,50101,수미,17568.0,30235500,1721.055328,2340.562914,1916.012658,987.213891,1282.500000,208.333333,2442.605634,22,28678.477528,25526.520718,23843.787309,18111.504723,2018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175762,202112하순,350301,익산,501,감자,50101,수미,200.0,380000,1900.000000,0.000000,0.000000,1900.000000,1900.000000,1900.000000,1900.000000,1,1252.555072,992.972973,1427.763333,10649.603946,2021
175806,202112하순,360301,순천,501,감자,50101,수미,8180.0,9698500,1185.635697,1813.513514,1219.521912,531.250000,925.000000,150.000000,2000.000000,32,1355.514250,1159.618557,1319.195205,0.000000,2021
175865,202112하순,371501,구미,501,감자,50101,수미,61700.0,99602900,1614.309562,1967.659574,1665.970149,1453.509892,1020.000000,110.000000,2140.000000,29,1628.584770,1003.604573,950.392157,4333.305519,2021
175918,202112하순,380201,울산,501,감자,50101,수미,11940.0,14015000,1173.785595,1926.359649,1128.508772,675.141844,820.307692,100.000000,2475.000000,17,966.313079,929.155844,969.491173,7032.383351,2021
175986,202112하순,380401,진주,501,감자,50101,수미,10000.0,21006100,2100.610000,0.000000,2453.634085,705.990099,955.000000,150.000000,2889.705882,10,1083.405405,919.677419,2155.222068,0.000000,2021

In [83]:
potato_df1 = potato1.groupby(['시점', '품목명']).mean(numeric_only=True).reset_index()
potato_df1

,시점,품목명,시장코드,품목코드,품종코드,총반입량(kg),총거래금액(원),평균가(원/kg),고가(20%) 평균가,중가(60%) 평균가,저가(20%) 평균가,중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
0,201801상순,감자,282369.571429,501.0,50101.0,173121.178571,2.954213e+08,1763.941835,2135.388609,1871.577198,1139.535550,1396.658338,452.020731,3083.719138,87.714286,99329.620076,27161.593244,21314.816559,12070.176215,2018.0
1,201801중순,감자,283451.714286,501.0,50101.0,146554.471429,2.617663e+08,1756.310004,2177.365953,1800.494239,1089.044543,1441.253457,510.595460,3094.150838,89.214286,1689.134552,184639.543875,19958.782387,11030.729217,2018.0
2,201801하순,감자,284558.400000,501.0,50101.0,132082.473333,2.498778e+08,1877.204699,2169.797213,1816.866108,1284.444375,1490.532646,585.632443,3753.340399,72.233333,1639.222670,92707.645405,19508.535628,10913.357611,2018.0
3,201802상순,감자,282369.571429,501.0,50101.0,200765.228571,4.317602e+08,2125.963165,2553.063567,2224.119453,1318.328050,1666.939195,493.313055,4072.803054,95.750000,1860.050456,1762.093736,21498.045362,12326.727328,2018.0
4,201802중순,감자,279861.000000,501.0,50101.0,94628.037037,2.040133e+08,2148.605466,2371.052522,2288.145887,1394.033152,1775.895260,745.267706,3429.704634,47.296296,2133.060603,1721.358523,233812.984878,12832.699595,2018.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,202111중순,감자,279097.961538,501.0,50101.0,92828.307692,1.122517e+08,1146.669434,1308.491391,1179.694154,655.904909,924.859725,246.102395,1702.263461,59.461538,1049.437985,969.216888,932.340061,51074.127330,2021.0
140,202111하순,감자,278705.576923,501.0,50101.0,92343.307692,1.231644e+08,1192.878667,1397.863261,1255.067330,768.295789,977.525705,275.565621,2362.815353,55.923077,1124.552982,1046.378871,992.357738,6026.997375,2021.0
141,202112상순,감자,278705.576923,501.0,50101.0,136502.615385,1.889315e+08,1362.526980,1545.874553,1437.655459,881.625611,1110.802396,356.618298,2069.263883,79.461538,1192.878667,990.836586,978.483166,6406.138644,2021.0
142,202112중순,감자,278705.576923,501.0,50101.0,97703.461538,1.287592e+08,1276.642744,1253.049877,1419.010662,809.613102,957.367503,271.356592,1893.542700,56.538462,1362.526980,1124.552982,1034.900209,6436.409040,2021.0
143,202112하순,감자,275049.760000,501.0,50101.0,133980.640000,2.106486e+08,1490.457520,1818.934794,1421.903786,941.202615,1252.148517,435.613686,2634.509512,73.680000,1321.366606,1232.722019,1005.812587,32766.494679,2021.0

In [84]:
potato_df1.describe()

,시장코드,품목코드,품종코드,총반입량(kg),총거래금액(원),평균가(원/kg),고가(20%) 평균가,중가(60%) 평균가,저가(20%) 평균가,중간가(원/kg),최저가(원/kg),최고가(원/kg),경매 건수,전순 평균가격(원) PreVious SOON,전달 평균가격(원) PreVious MMonth,전년 평균가격(원) PreVious YeaR,평년 평균가격(원) Common Year SOON,연도
count,144.000000,144.0,144.0,144.000000,1.440000e+02,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000,144.000000
mean,286363.404972,501.0,50101.0,212720.418284,2.588377e+08,1269.138955,1649.619624,1299.806698,730.701957,1033.118459,291.658048,3052.764111,143.176340,1909.577862,3307.942691,16089.451733,19778.449103,2019.500000
std,4531.042880,0.0,0.0,102587.425993,1.359964e+08,586.406193,701.167159,616.901217,382.094055,474.194848,173.284129,6984.422813,94.425379,8194.316505,17158.694084,40319.217463,24586.639995,1.121936
min,274006.041667,501.0,50101.0,61409.692308,9.312017e+07,580.157376,802.130562,610.601846,271.440911,481.696120,78.189157,1215.724502,27.538462,580.157388,586.739143,562.576861,2825.797275,2018.000000
25%,282877.841931,501.0,50101.0,151752.918135,1.498646e+08,884.492119,1164.507990,884.641926,466.171950,701.496151,177.793566,1681.376817,87.711640,851.610524,857.504336,899.495765,7879.788818,2018.750000
50%,287201.800000,501.0,50101.0,186721.514423,2.218396e+08,1148.697931,1441.521098,1179.529808,664.310495,947.040006,255.082406,2225.082434,111.596296,1120.265347,1113.975529,1389.489476,10593.962629,2019.500000
75%,289917.375000,501.0,50101.0,234512.784752,3.349454e+08,1499.661404,2020.445621,1561.222919,827.832699,1191.299045,353.074383,2826.211693,164.450461,1468.849241,1469.139491,6132.124906,16141.619989,2020.250000
max,293679.812500,501.0,50101.0,653790.956250,7.091919e+08,4315.574910,4704.310076,4510.722679,2711.187352,3453.131067,1177.086357,85201.881981,535.000000,99329.620076,184639.543875,233812.984878,115389.895155,2021.000000